sonar.projectKey=TuuuurProject_TuuuurWEB
sonar.organization=tuuuurproject

# Path is relative to the sonar-project.properties file
sonar.sources=src
sonar.tests=cypress,src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,cypress/**/*.cy.ts

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.config.ts,**/*.config.js,src/mocks/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info,.nyc_output/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info,.nyc_output/lcov.info
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,**/*.cy.ts,src/mocks/**

# Encoding
sonar.sourceEncoding=UTF-8
