name: Test, Build and Deploy dev branch

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/job_build.yaml
    secrets: inherit
