name: Test and Build develop branch

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    uses: ./.github/workflows/job_build.yaml
    secrets: inherit
