name: Build Workflow Release

on:
  workflow_call:
    secrets:
      DOCKER_LOGIN:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN  }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Push Docker Image
        run: make docker_build
