name: Build Workflow

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
        description: 'Docker image tag (e.g., preprod, latest)'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t tuuur_web:dev --build-arg BUILD_ENV=${{ inputs.image_tag }} --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} .
